In [4]:
import numpy as np # generating random symmetric matric
def symmetricmatrix(n):

    arr = np.random.randint(2, size=n*n)# randomly generate integers 0,1 of (n*n)

    arr = arr.reshape(n,n) #reshaping to n  by n matrix

    arr = np.tril(arr) + np.tril(arr, -1).T # because in this case all elements of a matrix are from same distribution (uniform in this case)

    return arr

In [5]:
n = int(input("Enter your value: ")) 
print(n)
rel = symmetricmatrix(n) #function call relation matrix 


Enter your value: 20
20


In [7]:
for i in range(0,len(rel)):
    rel[i][i]=1
print(rel)#relation between freinds '1' signifies they know each other,'0' represent the opposite.

[[1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0]
 [1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1]
 [1 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 1 0 1 1 1]
 [1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 1 0]
 [0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1]
 [0 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1]
 [1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1]
 [0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0]
 [0 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1]
 [0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1]
 [0 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0]
 [0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0]
 [1 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 1]
 [0 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 1 1]
 [0 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1]]


In [54]:
k = [] 
s = []
d = []
for j in range(0,len(rel)):         # reading row wise in rel matrix 
    sum =0
    arr1 = rel[j] 
    for i in range(0, len(arr1)):    # reading columns of row   
        sum = sum + arr1[i];         # adding the columns
    s.append(sum)                    # appending sum to k and k represents the number of friends known to a person.
    k.append(sum-1)                  # 1 is removed since it is conditional that for every friend, conditions should be checked,
    d.append((n-1)-(sum-1))          # Number of people not known by a person.k = sum-1

In [55]:
s                                    #sum 

[10, 11, 10, 6, 8, 9, 11, 11, 9, 13, 10, 9, 12, 10, 12, 10, 11, 12, 10, 12]

In [56]:
k                                    # k = sum -1 for a person k number of persons who know(excluding the person)


[9, 10, 9, 5, 7, 8, 10, 10, 8, 12, 9, 8, 11, 9, 11, 9, 10, 11, 9, 11]

In [57]:
d                                   #for a person no.of people who dont know(d) is atleast no.of people who know(k) 


[10, 9, 10, 14, 12, 11, 9, 9, 11, 7, 10, 11, 8, 10, 8, 10, 9, 8, 10, 8]

In [58]:
res = [] #comparing s and d with k
for t in range(0,n):
    if (d[t]<k[t]): # if d is not atlest k  then they are not invited since d should be  >= k 
        res.append(0)
    else:
        res.append(1)
        

In [59]:
res


[1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0]

Row/column of the matrix where 0 obtained in res is neglected.Therefore, friends who resulted "1" in res can be invited to party  

In [60]:
res.count(1)

11

In [61]:
res.count(0)

9